primary:
  extraEnvVars:
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "password"
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "username"
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "database"

readReplicas:
  extraEnvVars:
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "password"
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "username"
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: "microservices-secrets-postgresql"
          key: "database"

persistence:
  enabled: true
  storageClass: "standard"
  size: "10Gi"

# Configure service exposure
service:
  type: ClusterIP
  port: 5432

volumePermissions:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

extraEnvVars:
  - name: PG_TIMEZONE
    value: "UTC"
