# Default values for items-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: dzivkovic90t/microservices-items
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: "microservices-items"

env:
  - name: AppSettings__AuditLogService__BaseUrl
    value: http://microservices-audit-logs:3000
  - name: AppSettings__Database__Host
    valueFrom:
      secretKeyRef:
        name: microservices-secrets-postgresql
        key: host
  - name: AppSettings__Database__Port
    valueFrom:
      secretKeyRef:
        name: microservices-secrets-postgresql
        key: port
  - name: AppSettings__Database__Database
    valueFrom:
      secretKeyRef:
        name: microservices-secrets-postgresql
        key: database
  - name: AppSettings__Database__User
    valueFrom:
      secretKeyRef:
        name: microservices-secrets-postgresql
        key: username
  - name: AppSettings__Database__Password
    valueFrom:
      secretKeyRef:
        name: microservices-secrets-postgresql
        key: password

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
