image:
  repository: dzivkovic90t/microservices-migrations
  tag: latest
  pullPolicy: Always

job:
  backoffLimit: 3

database:
  url: jdbc:postgresql://postgres-release-postgresql.default.svc.cluster.local:5432/mydatabase
  username: myuser
  passwordSecret:
    name: microservices-secrets-postgresql
    key: password

resources: {}
