apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "nginx-charts.fullname" .}}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "test.local"
      http:
        paths:
          - pathType: Prefix
            path: /api/items
            backend:
              service:
                name: microservices-items
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/audit-logs
            backend:
              service:
                name: microservices-audit-logs
                port:
                  number: 3000
